### ISSUE TITLE
Add middleware or similar for Kubernetes probes

### ISSUE THREAD

**Issue by bittner** [vshn/django-probes#15]
As of today, this Django app only provides a way to ensure that a database, configured in your Django project, is reachable. The main use case for this is a [Kubernetes Init Container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/).

### Health checks

For the health checks after the startup phase, we usually suggest to implement the [Kubernetes probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) with the least impact that technically makes sense. For Python application running [uWSGI](https://pypi.org/project/uWSGI/) this is a check on the socket, e.g.

```yaml
      containers:
      - name: django
        ports:
        - name: uwsgi
          containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: uwsgi
          initialDelaySeconds: 13
        readinessProbe:
          tcpSocket:
            port: uwsgi
          initialDelaySeconds: 9
```

However, if someone for some specific reason wanted to do checks deeper into the Django application stack we may need to provide an appropriate way to call the application in a way that consumes few resources. (A management command will probably not do for this use case.)

### Other background reading

- [Kubernetes Health Checks in Django](https://www.ianlewis.org/en/kubernetes-health-checks-django) (@ianlewis, May 2017)
- [How to Avoid Shooting Yourself in the Foot](https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/) (@breckcs, Nov 2018)
